sudo: false
dist: trusty
language: rust
cache: cargo
rust: nightly-2019-08-21 # minimum required version for async/await

before_install:
  - cargo install mdbook --vers '0.3.1' --debug --force
  - cargo install mdbook-linkcheck --vers '0.3.1' --debug --force

script:
  - bash ci/spellcheck.sh list
  - mdbook build
  - cargo test --all --manifest-path=./examples/Cargo.toml --target-dir ./target

before_cache:
  - find ./target/debug -maxdepth 1 -type f -delete
  - rm -rf ./target/debug/incremental
  - rm -rf ./target/debug/{deps,.fingerprint}/[0-9][0-9]_[0-9][0-9]_*
  - rm -f ./target/.rustc_info.json

env:
  RUSTINFRA_DEPLOY_DIR: book/html
import:
  - rust-lang/simpleinfra/travis-configs/static-websites.yml

deploy:
  provider: pages
  local_dir: $RUSTINFRA_DEPLOY_DIR
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  on:
    branch: master
