sudo: false
dist: trusty
language: rust
cache: cargo
rust: nightly-2019-08-21 # minimum required version for async/await
addons:
  apt:
    packages:
      - aspell
      - aspell-en

before_install:
  - cargo install mdbook --vers '0.3.1' --debug --force
  - cargo install mdbook-linkcheck --vers '0.3.1' --debug --force

script:
  - bash ci/spellcheck.sh list
  - mdbook build
  - cargo test --all --manifest-path=./examples/Cargo.toml --target-dir ./target

env:
  RUSTINFRA_DEPLOY_DIR: book/html
import:
  - rust-lang/simpleinfra/travis-configs/static-websites.yml
