[package]
name = "02_03_timer"
version = "0.1.0"
authors = ["Taylor Cramer <cramertj@google.com>"]
edition = "2018"

[lib]

[dependencies]
futures-preview = { version = "=0.3.0-alpha.16", features = ["async-await", "nightly"] }
