[package]
name = "example_02_04_executor"
version = "0.1.0"
authors = ["Taylor Cramer <cramertj@google.com>"]
edition = "2021"

[lib]

[dependencies]
futures = "0.3"
timer_future = { package = "example_02_03_timer", path = "../02_03_timer" }
