[package]
name = "05_01_streams"
version = "0.1.0"
authors = ["Taylor Cramer <cramertj@google.com>"]
edition = "2018"

[lib]

[dev-dependencies]
futures-preview = { version = "=0.3.0-alpha.16", features = ["async-await", "nightly"] }
